// Termos de Uso e Politica de Privacidade (Paraguai). Cada secao e [titulo, texto]; no texto, "\n" separa paragrafos e
// linhas que comecam com "- " viram marcadores.
//
// Base legal usada (Republica do Paraguai): Constituicao Nacional (arts. 33, 36 e 135 - intimidade, inviolabilidade
// das comunicacoes e habeas data); Lei 4868/2013 (Comercio Eletronico); Lei 4017/2010 (validade juridica da assinatura
// eletronica, mensagens de dados e expediente eletronico); Lei 1334/1998 (Defesa do Consumidor e do Usuario, SEDECO);
// Lei 1328/1998 (Direito de Autor e Conexos); Lei 6380/2019 (Sistema Tributario - IVA); Lei 2169/2003 (maioridade aos
// 18 anos); Lei 6534/2020 (Protecao de Dados Pessoais Creditorios).
//
// IMPORTANTE: elaborado como modelo de boa-fe; deve ser revisado por advogado matriculado no Paraguai antes de ser
// tratado como definitivo. Se o conteudo mudar de forma relevante, aumente TERMOS_VERSAO em negocio.js (todos
// precisam aceitar de novo). Dados do titular (razao social, RUC, endereco) entram sozinhos se as variaveis de ambiente
// EMPRESA_NOME, EMPRESA_RUC e EMPRESA_ENDERECO estiverem preenchidas.
const { NOME_APP, EMAIL_SUPORTE, TRIAL_DIAS } = require('./negocio');

function fmt(n) { return String(n).replace(/\B(?=(\d{3})+(?!\d))/g, '.'); }

// Identificacao do titular (opcional, vem do ambiente): " Titular: Fulano S.A. (RUC 80000000-0), Rua X, Assuncao."
function identificacao(l) {
    const nome = process.env.EMPRESA_NOME, ruc = process.env.EMPRESA_RUC, ender = process.env.EMPRESA_ENDERECO;
    if (!nome) return '';
    const rotulo = l === 'en' ? 'Operator' : 'Titular';
    return ` ${rotulo}: ${nome}${ruc ? ` (RUC ${ruc})` : ''}${ender ? `, ${ender}` : ''}.`;
}

function textos(lang, precos) {
    const idioma = String(lang || '').toLowerCase();
    const l = idioma.startsWith('es') ? 'es' : (idioma.startsWith('en') ? 'en' : 'pt');
    const contato = EMAIL_SUPORTE || '—';
    const b = fmt(precos.basico), p = fmt(precos.premium), o = fmt(precos.pro || 0);
    const app = NOME_APP;
    const dias = TRIAL_DIAS;
    const ident = identificacao(l);

    if (l === 'es') {
        return {
            termos: [
                ['1. Quiénes somos y aceptación', `${app} es un servicio en línea de gestión financiera personal, operado por su titular (en adelante, "el Prestador"). Contacto: ${contato}.${ident}\nAl crear una cuenta, marcar la casilla de aceptación o utilizar el servicio, usted (en adelante, "el Usuario") declara haber leído y aceptar estos Términos de Uso y la Política de Privacidad. La aceptación por medios electrónicos tiene plena validez conforme a la Ley N° 4868/2013 de Comercio Electrónico y a la Ley N° 4017/2010 de validez jurídica de la firma electrónica, los mensajes de datos y el expediente electrónico. Si no está de acuerdo, no utilice el servicio.`],
                ['2. Definiciones', `- Servicio: la aplicación web y móvil ${app}, sus funciones y el Chat IA.\n- Cuenta: el registro personal del Usuario.\n- Plan: Básico, Premium o Pro, cada uno con las funciones y los límites indicados en la pantalla de planes.\n- Contenido del Usuario: los datos que el Usuario registra (cuentas, movimientos, categorías, mensajes, fotos y audios).\n- Prueba gratuita: el período de uso sin costo descrito en la cláusula 6.`],
                ['3. El servicio y su alcance', `${app} permite registrar y organizar ingresos, gastos, cuentas, categorías, transferencias y presupuestos, ver informes y, según el plan, usar un asistente de inteligencia artificial.\nEl Servicio es una herramienta de organización. No presta asesoría financiera, contable, tributaria, legal ni de inversión; no es una entidad financiera ni de crédito, no intermedia pagos ni custodia dinero. Los saldos y resultados que se muestran dependen de los datos que el propio Usuario registra, y las decisiones que tome con ellos son de su exclusiva responsabilidad.`],
                ['4. Cuenta, edad y seguridad', `Para crear una Cuenta el Usuario debe ser mayor de 18 años (mayoría de edad conforme a la Ley N° 2169/2003) y tener capacidad para contratar. Debe proporcionar datos verdaderos y mantenerlos actualizados.\nEl Usuario es responsable de la confidencialidad de su contraseña y de toda la actividad realizada con su Cuenta, y debe avisar de inmediato ante cualquier uso no autorizado. Cada Cuenta es personal e intransferible.`],
                ['5. Planes, precios e IVA', `Los planes y precios vigentes se muestran en la pantalla de planes. Precios mensuales sin IVA: Básico Gs. ${b}, Premium Gs. ${p} y Pro Gs. ${o}; el pago anual equivale a 10 meses (dos meses de descuento). Los precios están expresados en guaraníes y NO incluyen el Impuesto al Valor Agregado (IVA), que se agrega a la tasa legal vigente (actualmente 10 %) conforme a la Ley N° 6380/2019 y sus modificaciones. El precio final con IVA se informa antes de confirmar cada pedido y se emite el comprobante correspondiente según la normativa tributaria.\nCada plan incluye funciones y límites de uso distintos (por ejemplo, cantidad de cuentas bancarias, mensajes de IA por mes y registros por foto o audio por mes). El Prestador puede modificar precios, funciones o límites con aviso previo razonable; el cambio no afecta los períodos ya pagados.`],
                ['6. Prueba gratuita', `Las cuentas nuevas eligen un plan (Básico, Premium o Pro) y lo usan sin costo durante ${dias} días, sin necesidad de tarjeta. La prueba gratuita se concede una sola vez por Cuenta y por persona; durante la prueba el Usuario puede cambiar el plan en prueba sin que se reinicie el plazo. El Prestador puede negar o dar por terminada la prueba si detecta cuentas duplicadas creadas para repetirla.\nAl vencer la prueba, el acceso a las funciones del Servicio queda suspendido hasta que el Usuario contrate un plan; sus datos se conservan y vuelven a estar disponibles al activarse el plan.`],
                ['7. Contratación, pago y renovación', `La contratación se solicita desde la pantalla de planes; el Prestador se pone en contacto por teléfono o WhatsApp con los datos de pago (transferencia, Tigo Money u otros medios habilitados) y activa el plan una vez confirmado el pago. El plan se paga por período adelantado, mensual o anual. No se realiza ningún cobro automático sin autorización expresa del Usuario.\nSi un período pagado vence sin renovación, la Cuenta pasa a modo de solo lectura: el Usuario puede consultar sus datos, pero no registrar nuevos movimientos, hasta que vuelva a pagar.`],
                ['8. Cancelación, desistimiento y reembolsos', `El Usuario puede dejar de usar el Servicio y cancelar su suscripción en cualquier momento; el acceso continúa hasta el fin del período ya pagado y no se renueva. Los pagos de períodos ya iniciados no son reembolsables, salvo error del Prestador, cobro indebido o cuando la ley disponga lo contrario. Nada de lo previsto en estos Términos limita los derechos irrenunciables que la Ley N° 1334/1998 de Defensa del Consumidor y del Usuario reconoce a los consumidores, incluido el de reclamar ante la Secretaría de Defensa del Consumidor y el Usuario (SEDECO).`],
                ['9. Uso aceptable', `Está prohibido:\n- Usar el Servicio con fines ilícitos o para registrar actividades que constituyan hechos punibles.\n- Intentar acceder a cuentas o datos de otros usuarios, eludir los límites de cada plan o vulnerar la seguridad del Servicio.\n- Sobrecargar la infraestructura, extraer datos de forma automatizada y masiva, hacer ingeniería inversa o realizar ataques.\n- Revender, sublicenciar o compartir el acceso a la Cuenta con terceros.\n- Usar el Chat IA para fines ajenos a las finanzas personales o intentar manipularlo para obtener información interna del sistema.\n- Publicar en la Comunidad contenido ilícito u ofensivo, que infrinja derechos de terceros o que contenga datos personales ajenos.`],
                ['10. Inteligencia artificial', `El Chat IA usa modelos de inteligencia artificial de terceros para entender mensajes de texto, fotos de comprobantes y audios, registrar movimientos y responder preguntas sobre los datos del Usuario.\n- Las respuestas y los registros pueden contener errores. El Usuario debe revisar el valor, la fecha, la cuenta y la categoría de cada registro; los registros hechos por la IA pueden revertirse durante unos segundos desde la propia pantalla y editarse después como cualquier otro.\n- Las respuestas de la IA son informativas y no constituyen asesoría financiera, contable ni de inversión.\n- Cada plan tiene un límite mensual de mensajes y de registros por foto o audio; al alcanzarlo, esas funciones se reanudan el mes siguiente o con un plan superior.\n- El Usuario no debe enviar fotos o audios con datos sensibles de terceros ni información que no necesite registrar. Las fotos y los audios se procesan solo para ese fin y no se guardan en el Servicio (ver la Política de Privacidad).`],
                ['11. Datos del Usuario', `El Contenido del Usuario le pertenece. El Usuario otorga al Prestador una licencia limitada, no exclusiva y revocable, solo para alojar, procesar y mostrar esos datos con el fin de prestar el Servicio. El Prestador no vende los datos ni los usa para publicidad.\nEl Usuario puede corregir sus datos, eliminar su Cuenta en cualquier momento desde Configuración (lo que borra definitivamente sus cuentas, categorías y movimientos) y, en el Plan Pro, exportar y respaldar su información desde el sistema; en los demás planes puede solicitar una copia por el contacto indicado.`],
                ['12. Propiedad intelectual', `El software, el diseño, las marcas, los textos y demás elementos de ${app} pertenecen al Prestador o a sus licenciantes y están protegidos por la Ley N° 1328/1998 de Derechos de Autor y Derechos Conexos y demás normas aplicables. Estos Términos no transfieren al Usuario ningún derecho sobre ellos, salvo el de usar el Servicio mientras su Cuenta esté activa.`],
                ['13. Disponibilidad y copias de seguridad', `El Prestador realiza esfuerzos razonables para mantener el Servicio disponible y los datos protegidos, pero no garantiza un funcionamiento ininterrumpido ni libre de errores: pueden existir mantenimientos, fallas de terceros (hospedaje, correo, conexión) o causas de fuerza mayor.\nEl modo sin conexión guarda temporalmente los registros en el dispositivo hasta enviarlos; el Usuario debe volver a conectarse para completar el envío y no borrar los datos del navegador antes. Se recomienda exportar copias periódicas (Plan Pro) o solicitarlas.`],
                ['14. Limitación de responsabilidad', `En la medida permitida por la ley, el Prestador no responde por daños indirectos, lucro cesante o pérdidas derivadas de decisiones tomadas con base en la información del Servicio, de datos mal registrados por el Usuario, de errores de la IA no revisados, de fallas de terceros o del uso indebido de la Cuenta. Cuando la ley no permita excluir o limitar la responsabilidad, en especial frente a consumidores, se aplicará el límite mínimo obligatorio, y la responsabilidad del Prestador, cuando exista, se limitará al valor efectivamente pagado por el Usuario en los 12 meses anteriores al hecho. Nada de esto afecta los derechos irrenunciables del consumidor.`],
                ['15. Suspensión y terminación', `El Prestador puede suspender o cancelar Cuentas que incumplan estos Términos, que presenten uso fraudulento o abusivo, o por orden de autoridad competente, avisando al Usuario siempre que sea posible. Si la cancelación se debe a un incumplimiento del Usuario, no hay reembolso del período en curso. El Usuario puede solicitar la exportación de sus datos (cuando su plan lo permita) o su eliminación.`],
                ['16. Cambios en los Términos', `El Prestador puede actualizar estos Términos y la Política de Privacidad. Los cambios relevantes se informan dentro del Servicio y se solicitará una nueva aceptación para seguir usándolo. La versión vigente figura en la parte superior de cada documento.`],
                ['17. Comunicaciones', `El Usuario acepta recibir las comunicaciones electrónicas necesarias para el Servicio (confirmación de correo, recuperación de contraseña, avisos de suscripción y de seguridad, y avisos de vencimiento si los activó) y ser contactado por correo, teléfono o WhatsApp para coordinar la contratación de un plan. Los avisos de vencimiento pueden desactivarse en Configuración.`],
                ['18. Ley aplicable, jurisdicción y reclamos', `Estos Términos se rigen por las leyes de la República del Paraguay. Ante cualquier controversia, las partes procurarán resolverla amistosamente, contactando primero al Prestador. De no lograrse, serán competentes los tribunales ordinarios de la ciudad de Asunción, sin perjuicio del derecho del consumidor de acudir a la SEDECO y a los foros que la Ley N° 1334/1998 le reconoce.`],
                ['19. Disposiciones generales', `Si alguna cláusula fuera declarada inválida, las demás seguirán vigentes. La falta de ejercicio de un derecho no implica renuncia. Estos Términos y la Política de Privacidad constituyen el acuerdo completo entre el Usuario y el Prestador sobre el Servicio.`],
                ['20. Contacto', `Consultas, reclamos y solicitudes: ${contato}.`]
            ],
            privacidade: [
                ['1. Responsable y marco legal', `El responsable del tratamiento de los datos personales es el Prestador de ${app}. Contacto: ${contato}.${ident}\nEl tratamiento respeta los derechos a la intimidad y a la protección de los datos personales reconocidos por la Constitución Nacional (arts. 33 y 36 y la garantía del hábeas data del art. 135), la Ley N° 4868/2013 de Comercio Electrónico, la Ley N° 1334/1998 de Defensa del Consumidor y del Usuario y, en lo que resulte aplicable, la Ley N° 6534/2020 de Protección de Datos Personales Crediticios, además de las demás normas vigentes en la República del Paraguay.`],
                ['2. Datos que recopilamos', `- Cuenta: nombre, correo electrónico, contraseña (almacenada cifrada con hash, nunca en texto), idioma, moneda, tema y fecha de aceptación de los términos. Si inicia sesión con Google: su nombre, correo verificado e identificador de Google.\n- Contacto de contratación: teléfono (solo si solicita un plan).\n- Datos financieros que usted registra: cuentas, saldos, movimientos, categorías, presupuestos y recordatorios.\n- Chat IA: sus mensajes y las respuestas (para mostrar el historial; puede borrar las conversaciones) y, solo mientras se procesan, las fotos y los audios que envíe.\n- Uso y seguridad: fechas de acceso, dirección IP, tipo de navegador o dispositivo, intentos de ingreso, dispositivos conectados y contadores de uso por plan.\n- Comunidad: las publicaciones, comentarios e imágenes que usted decida publicar.`],
                ['3. Para qué usamos los datos', `- Prestar el Servicio y ejecutar el contrato (registrar, calcular saldos, informes, sincronización y modo sin conexión).\n- Autenticarlo y proteger la Cuenta, y prevenir fraudes y abusos.\n- Enviar correos del Servicio (confirmación, recuperación de contraseña, avisos de suscripción) y, si los activó, avisos de vencimiento en el dispositivo.\n- Contactarlo por teléfono o WhatsApp para coordinar el pago y la activación de un plan.\n- Gestionar planes, cobros, comprobantes y obligaciones tributarias y contables.\n- Controlar los límites de uso de cada plan y mejorar el producto con estadísticas agregadas.\nNo vendemos sus datos ni los usamos para publicidad de terceros.`],
                ['4. Con quién los compartimos', `Solo con proveedores necesarios para operar el Servicio, que reciben únicamente lo indispensable para su función:\n- Hospedaje y base de datos (Hostinger).\n- Envío de correos del Servicio (proveedor de correo).\n- Inicio de sesión con Google, si usted lo elige.\n- Proveedores de inteligencia artificial y de transcripción de audio, solo cuando usa el Chat IA: reciben el texto, las fotos o los audios de esa consulta y los datos financieros mínimos necesarios para responder.\n- Notificaciones push del navegador o dispositivo, si las activa.\nTambién podemos revelar datos cuando una autoridad competente lo exija conforme a la ley. Algunos proveedores pueden estar fuera del Paraguay; en ese caso exigimos medidas de seguridad adecuadas y limitamos los datos compartidos.`],
                ['5. Cuánto tiempo los conservamos', `Mientras su Cuenta esté activa. Al eliminarla, borramos sus datos personales y financieros, incluidas las conversaciones del Chat IA y los dispositivos; solo conservamos los registros de pago por el plazo que exijan las normas tributarias y contables, desvinculados de su identidad en la medida de lo posible. Las fotos y los audios enviados a la IA no se guardan después de procesarse. Los registros técnicos de seguridad se conservan por un tiempo limitado.`],
                ['6. Sus derechos', `Usted puede, en cualquier momento: acceder a sus datos; rectificarlos o actualizarlos; solicitar su supresión; oponerse a ciertos tratamientos y retirar su consentimiento; y exportarlos (Plan Pro desde Configuración; en los demás planes, a pedido). Estos derechos incluyen la acción de hábeas data prevista en el art. 135 de la Constitución Nacional.\nPuede corregir su perfil y eliminar su Cuenta directamente en Configuración; para otras solicitudes escriba a ${contato}. Responderemos en un plazo razonable y, en todo caso, dentro del que establezca la ley. Si considera que sus derechos no fueron atendidos, puede acudir a las autoridades competentes.`],
                ['7. Seguridad', `Aplicamos medidas técnicas y organizativas razonables: contraseñas con hash, conexión cifrada (HTTPS), sesiones con cookies protegidas, protección contra solicitudes falsificadas (CSRF), limitación de intentos de ingreso, aislamiento de datos por usuario y acceso restringido a la base de datos. Ningún sistema es infalible; si ocurriera un incidente que afecte sus datos personales, se lo informaremos sin demora indebida y tomaremos medidas para mitigarlo.`],
                ['8. Cookies y almacenamiento en su dispositivo', `Usamos una cookie técnica de sesión (necesaria para mantener su acceso) y el almacenamiento local del navegador para preferencias (por ejemplo, ocultar saldos o el tema). Para el modo sin conexión y la instalación como aplicación, el dispositivo guarda copia de páginas y de sus datos y una cola de registros pendientes de envío; esos datos se borran al cerrar sesión y no se comparten. No usamos cookies de publicidad ni de seguimiento de terceros.`],
                ['9. Notificaciones', `Los avisos de vencimiento son opcionales: usted los activa y puede desactivarlos en Configuración › Recordatorios. Los correos del Servicio son los necesarios para operar la Cuenta.`],
                ['10. Menores de edad', `El Servicio no está dirigido a menores de 18 años y no recopilamos sus datos intencionalmente. Si tomamos conocimiento de una cuenta de un menor, la eliminaremos.`],
                ['11. Cambios en esta política', `Podemos actualizar esta Política. Los cambios relevantes se informan dentro del Servicio y se solicitará una nueva aceptación cuando corresponda.`],
                ['12. Contacto', `Consultas y ejercicio de derechos: ${contato}.`]
            ],
            aviso: 'Última actualización: octubre de 2026. Rige la legislación de la República del Paraguay.'
        };
    }

    if (l === 'en') {
        return {
            termos: [
                ['1. Who we are and acceptance', `${app} is an online personal finance management service run by its owner (the "Provider"). Contact: ${contato}.${ident}\nBy creating an account, ticking the acceptance box or using the service, you (the "User") declare that you have read and accept these Terms of Use and the Privacy Policy. Acceptance by electronic means is fully valid under Law No. 4868/2013 on Electronic Commerce and Law No. 4017/2010 on the legal validity of electronic signatures, data messages and electronic files. If you do not agree, do not use the service.`],
                ['2. Definitions', `- Service: the ${app} web and mobile application, its features and the AI Chat.\n- Account: the User's personal registration.\n- Plan: Basic, Premium or Pro, each with the features and limits shown on the plans screen.\n- User Content: the data the User records (accounts, entries, categories, messages, photos and audio).\n- Free trial: the no-cost period described in clause 6.`],
                ['3. The service and its scope', `${app} lets you record and organize income, expenses, accounts, categories, transfers and budgets, view reports and, depending on the plan, use an artificial intelligence assistant.\nThe Service is an organizing tool. It does not provide financial, accounting, tax, legal or investment advice; it is not a financial or credit institution and it does not intermediate payments or hold money. The balances and results shown depend on the data the User records, and any decision made with them is solely the User's responsibility.`],
                ['4. Account, age and security', `To create an Account the User must be over 18 (the age of majority under Law No. 2169/2003) and have the capacity to enter into contracts. The User must provide true information and keep it up to date.\nThe User is responsible for keeping the password confidential and for all activity under the Account, and must notify the Provider immediately of any unauthorized use. Each Account is personal and non-transferable.`],
                ['5. Plans, prices and VAT', `Current plans and prices are shown on the plans screen. Monthly prices excluding VAT: Basic Gs. ${b}, Premium Gs. ${p} and Pro Gs. ${o}; the annual payment equals 10 months (two months free). Prices are in guaraníes and do NOT include Value Added Tax (VAT), which is added at the legal rate in force (currently 10%) under Law No. 6380/2019 and its amendments. The final price with VAT is shown before each order is confirmed, and the corresponding receipt is issued in accordance with tax rules.\nEach plan includes different features and usage limits (for example, number of bank accounts, AI messages per month and photo or voice entries per month). The Provider may change prices, features or limits with reasonable prior notice; changes do not affect periods already paid.`],
                ['6. Free trial', `New accounts choose a plan (Basic, Premium or Pro) and use it free of charge for ${dias} days, with no card required. The free trial is granted once per Account and per person; during the trial the User may switch the plan on trial without the deadline restarting. The Provider may refuse or end the trial if it detects duplicate accounts created to repeat it.\nWhen the trial ends, access to the Service's features is suspended until the User subscribes to a plan; the data is kept and becomes available again when the plan is activated.`],
                ['7. Subscribing, payment and renewal', `A subscription is requested from the plans screen; the Provider then contacts the User by phone or WhatsApp with the payment details (bank transfer, Tigo Money or other enabled methods) and activates the plan once payment is confirmed. The plan is paid in advance, monthly or annually. No automatic charge is made without the User's express authorization.\nIf a paid period ends without renewal, the Account becomes read-only: the User can view their data but cannot add new entries until they pay again.`],
                ['8. Cancellation, withdrawal and refunds', `The User may stop using the Service and cancel the subscription at any time; access continues until the end of the period already paid and is not renewed. Payments for periods already started are non-refundable, except for a Provider error, an improper charge or where the law provides otherwise. Nothing in these Terms limits the non-waivable rights that Law No. 1334/1998 on Consumer and User Protection grants to consumers, including the right to complain to the Consumer and User Protection Secretariat (SEDECO).`],
                ['9. Acceptable use', `The following is prohibited:\n- Using the Service for unlawful purposes or to record activities that constitute criminal offenses.\n- Trying to access other users' accounts or data, getting around the limits of each plan or breaching the Service's security.\n- Overloading the infrastructure, bulk automated data scraping, reverse engineering or attacks.\n- Reselling, sublicensing or sharing Account access with third parties.\n- Using the AI Chat for purposes unrelated to personal finance or trying to manipulate it to obtain internal system information.\n- Posting in the Community content that is unlawful or offensive, infringes third-party rights or contains other people's personal data.`],
                ['10. Artificial intelligence', `The AI Chat uses third-party artificial intelligence models to understand text messages, receipt photos and voice recordings, record entries and answer questions about the User's data.\n- Answers and entries may contain errors. The User must check the amount, date, account and category of each entry; entries made by the AI can be undone for a few seconds on the same screen and edited afterwards like any other.\n- AI answers are informational and are not financial, accounting or investment advice.\n- Each plan has a monthly limit of messages and of photo or voice entries; once reached, those features resume the next month or with a higher plan.\n- The User must not send photos or recordings containing third parties' sensitive data or information they do not need to record. Photos and recordings are processed only for that purpose and are not stored in the Service (see the Privacy Policy).`],
                ['11. User data', `User Content belongs to the User. The User grants the Provider a limited, non-exclusive, revocable license solely to host, process and display that data in order to provide the Service. The Provider does not sell the data or use it for advertising.\nThe User may correct their data, delete their Account at any time from Settings (which permanently deletes their accounts, categories and entries) and, on the Pro Plan, export and back up their information from the system; on other plans they may request a copy through the contact below.`],
                ['12. Intellectual property', `The software, design, trademarks, texts and other elements of ${app} belong to the Provider or its licensors and are protected by Law No. 1328/1998 on Copyright and Related Rights and other applicable rules. These Terms do not transfer any right in them to the User, other than the right to use the Service while the Account is active.`],
                ['13. Availability and backups', `The Provider makes reasonable efforts to keep the Service available and the data protected, but does not guarantee uninterrupted or error-free operation: there may be maintenance, third-party failures (hosting, e-mail, connectivity) or force majeure.\nOffline mode temporarily stores entries on the device until they are sent; the User must reconnect to complete the sending and must not clear browser data beforehand. Regular exported copies (Pro Plan) or copy requests are recommended.`],
                ['14. Limitation of liability', `To the extent permitted by law, the Provider is not liable for indirect damages, loss of profit or losses arising from decisions made on the basis of the Service's information, data incorrectly recorded by the User, unreviewed AI errors, third-party failures or misuse of the Account. Where the law does not allow liability to be excluded or limited, especially with respect to consumers, the mandatory minimum limit applies, and the Provider's liability, where it exists, is limited to the amount actually paid by the User in the 12 months before the event. None of this affects the consumer's non-waivable rights.`],
                ['15. Suspension and termination', `The Provider may suspend or cancel Accounts that breach these Terms, show fraudulent or abusive use, or by order of a competent authority, notifying the User whenever possible. If cancellation is due to the User's breach, the current period is not refunded. The User may request the export of their data (where their plan allows it) or its deletion.`],
                ['16. Changes to the Terms', `The Provider may update these Terms and the Privacy Policy. Relevant changes are announced within the Service and a new acceptance will be requested to keep using it. The current version is shown at the top of each document.`],
                ['17. Communications', `The User agrees to receive the electronic communications necessary for the Service (e-mail confirmation, password recovery, subscription and security notices, and due-date reminders if enabled) and to be contacted by e-mail, phone or WhatsApp to arrange a plan subscription. Due-date reminders can be turned off in Settings.`],
                ['18. Governing law, jurisdiction and complaints', `These Terms are governed by the laws of the Republic of Paraguay. For any dispute, the parties will try to settle it amicably, first contacting the Provider. Failing that, the ordinary courts of the city of Asunción shall have jurisdiction, without prejudice to the consumer's right to go to SEDECO and to the forums recognized by Law No. 1334/1998.`],
                ['19. General provisions', `If any clause is declared invalid, the others remain in force. Failure to exercise a right is not a waiver. These Terms and the Privacy Policy are the entire agreement between the User and the Provider regarding the Service.`],
                ['20. Contact', `Questions, complaints and requests: ${contato}.`]
            ],
            privacidade: [
                ['1. Controller and legal framework', `The controller of personal data is the Provider of ${app}. Contact: ${contato}.${ident}\nProcessing respects the rights to privacy and to the protection of personal data recognized by the National Constitution (arts. 33 and 36 and the habeas data guarantee of art. 135), Law No. 4868/2013 on Electronic Commerce, Law No. 1334/1998 on Consumer and User Protection and, where applicable, Law No. 6534/2020 on the Protection of Personal Credit Data, as well as the other rules in force in the Republic of Paraguay.`],
                ['2. Data we collect', `- Account: name, e-mail, password (stored as a hash, never in plain text), language, currency, theme and the date you accepted the terms. If you sign in with Google: your name, verified e-mail and Google identifier.\n- Subscription contact: phone number (only if you request a plan).\n- Financial data you record: accounts, balances, entries, categories, budgets and reminders.\n- AI Chat: your messages and the answers (to show the history; you can delete conversations) and, only while they are processed, the photos and recordings you send.\n- Usage and security: access dates, IP address, browser or device type, sign-in attempts, connected devices and per-plan usage counters.\n- Community: the posts, comments and images you choose to publish.`],
                ['3. What we use the data for', `- To provide the Service and perform the contract (recording, balances, reports, synchronization and offline mode).\n- To authenticate you, protect the Account and prevent fraud and abuse.\n- To send Service e-mails (confirmation, password recovery, subscription notices) and, if you enabled them, due-date reminders on your device.\n- To contact you by phone or WhatsApp to arrange payment and activation of a plan.\n- To manage plans, payments, receipts and tax and accounting obligations.\n- To enforce each plan's usage limits and improve the product using aggregated statistics.\nWe do not sell your data or use it for third-party advertising.`],
                ['4. Who we share it with', `Only with providers needed to operate the Service, who receive just what is necessary for their function:\n- Hosting and database (Hostinger).\n- Sending Service e-mails (e-mail provider).\n- Google sign-in, if you choose it.\n- Artificial intelligence and audio transcription providers, only when you use the AI Chat: they receive the text, photos or recordings of that request and the minimum financial data needed to answer.\n- Browser or device push notifications, if you enable them.\nWe may also disclose data when a competent authority requires it by law. Some providers may be outside Paraguay; in that case we require adequate security measures and limit the data shared.`],
                ['5. How long we keep it', `While your Account is active. When you delete it, we erase your personal and financial data, including AI Chat conversations and devices; we only keep payment records for the period required by tax and accounting rules, detached from your identity as far as possible. Photos and recordings sent to the AI are not kept after processing. Technical security logs are kept for a limited time.`],
                ['6. Your rights', `You may, at any time: access your data; rectify or update it; request its deletion; object to certain processing and withdraw consent; and export it (Pro Plan from Settings; on other plans, on request). These rights include the habeas data action provided for in art. 135 of the National Constitution.\nYou can correct your profile and delete your Account directly in Settings; for other requests write to ${contato}. We will respond within a reasonable time and, in any case, within the time set by law. If you believe your rights have not been honored, you may go to the competent authorities.`],
                ['7. Security', `We apply reasonable technical and organizational measures: hashed passwords, encrypted connections (HTTPS), sessions with protected cookies, protection against forged requests (CSRF), limits on sign-in attempts, per-user data isolation and restricted database access. No system is infallible; if an incident affecting your personal data occurs, we will inform you without undue delay and take steps to mitigate it.`],
                ['8. Cookies and storage on your device', `We use one technical session cookie (needed to keep you signed in) and the browser's local storage for preferences (for example, hiding balances or the theme). For offline mode and installing the app, the device stores a copy of pages and of your data and a queue of entries waiting to be sent; this data is deleted when you sign out and is not shared. We do not use advertising or third-party tracking cookies.`],
                ['9. Notifications', `Due-date reminders are optional: you turn them on and can turn them off in Settings › Reminders. Service e-mails are only those needed to operate the Account.`],
                ['10. Minors', `The Service is not directed to people under 18 and we do not intentionally collect their data. If we learn of a minor's account, we will delete it.`],
                ['11. Changes to this policy', `We may update this Policy. Relevant changes are announced within the Service and a new acceptance will be requested when applicable.`],
                ['12. Contact', `Questions and exercising your rights: ${contato}.`]
            ],
            aviso: 'Last updated: October 2026. Governed by the laws of the Republic of Paraguay.'
        };
    }

    return {
        termos: [
            ['1. Quem somos e aceitação', `O ${app} é um serviço online de gestão financeira pessoal, operado pelo seu titular (o "Prestador"). Contato: ${contato}.${ident}\nAo criar uma conta, marcar a caixa de aceite ou usar o serviço, você (o "Usuário") declara ter lido e aceitar estes Termos de Uso e a Política de Privacidade. A aceitação por meios eletrônicos tem plena validade conforme a Lei nº 4.868/2013 de Comércio Eletrônico e a Lei nº 4.017/2010 de validade jurídica da assinatura eletrônica, das mensagens de dados e do expediente eletrônico (Paraguai). Se não concordar, não use o serviço.`],
            ['2. Definições', `- Serviço: o aplicativo web e móvel ${app}, suas funções e o Chat IA.\n- Conta: o cadastro pessoal do Usuário.\n- Plano: Básico, Premium ou Pro, cada um com as funções e os limites mostrados na tela de planos.\n- Conteúdo do Usuário: os dados que o Usuário registra (contas, lançamentos, categorias, mensagens, fotos e áudios).\n- Teste grátis: o período de uso sem custo descrito na cláusula 6.`],
            ['3. O serviço e seu alcance', `O ${app} permite registrar e organizar receitas, despesas, contas, categorias, transferências e orçamentos, ver relatórios e, conforme o plano, usar um assistente de inteligência artificial.\nO Serviço é uma ferramenta de organização. Não presta consultoria financeira, contábil, tributária, jurídica nem de investimentos; não é instituição financeira nem de crédito, não intermedeia pagamentos nem guarda dinheiro. Os saldos e resultados exibidos dependem dos dados que o próprio Usuário registra, e as decisões tomadas com eles são de sua exclusiva responsabilidade.`],
            ['4. Conta, idade e segurança', `Para criar uma Conta o Usuário deve ser maior de 18 anos (maioridade conforme a Lei nº 2.169/2003 do Paraguai) e ter capacidade para contratar. Deve fornecer dados verdadeiros e mantê-los atualizados.\nO Usuário é responsável pelo sigilo da senha e por toda a atividade feita com a sua Conta, e deve avisar imediatamente sobre qualquer uso não autorizado. Cada Conta é pessoal e intransferível.`],
            ['5. Planos, preços e IVA', `Os planos e preços vigentes aparecem na tela de planos. Preços mensais sem IVA: Básico Gs. ${b}, Premium Gs. ${p} e Pro Gs. ${o}; o pagamento anual equivale a 10 meses (dois meses de desconto). Os preços são em guaranis e NÃO incluem o Imposto sobre o Valor Agregado (IVA), que é acrescido pela alíquota legal vigente (atualmente 10 %) conforme a Lei nº 6.380/2019 e suas alterações. O preço final com IVA é informado antes de confirmar cada pedido e o comprovante correspondente é emitido conforme a norma tributária.\nCada plano inclui funções e limites de uso diferentes (por exemplo, quantidade de contas bancárias, mensagens de IA por mês e registros por foto ou áudio por mês). O Prestador pode alterar preços, funções ou limites com aviso prévio razoável; a mudança não afeta períodos já pagos.`],
            ['6. Teste grátis', `Contas novas escolhem um plano (Básico, Premium ou Pro) e o usam sem custo por ${dias} dias, sem necessidade de cartão. O teste grátis é concedido uma única vez por Conta e por pessoa; durante o teste o Usuário pode trocar o plano em teste sem reiniciar o prazo. O Prestador pode negar ou encerrar o teste se detectar contas duplicadas criadas para repeti-lo.\nAo fim do teste, o acesso às funções do Serviço fica suspenso até o Usuário contratar um plano; os dados são mantidos e voltam a ficar disponíveis quando o plano for ativado.`],
            ['7. Contratação, pagamento e renovação', `A contratação é solicitada na tela de planos; o Prestador entra em contato por telefone ou WhatsApp com os dados de pagamento (transferência, Tigo Money ou outros meios habilitados) e ativa o plano depois de confirmado o pagamento. O plano é pago por período adiantado, mensal ou anual. Nenhuma cobrança automática é feita sem autorização expressa do Usuário.\nSe um período pago terminar sem renovação, a Conta passa ao modo somente leitura: o Usuário consulta seus dados, mas não registra novos lançamentos, até pagar novamente.`],
            ['8. Cancelamento, desistência e reembolsos', `O Usuário pode deixar de usar o Serviço e cancelar a assinatura a qualquer momento; o acesso continua até o fim do período já pago e não é renovado. Pagamentos de períodos já iniciados não são reembolsáveis, salvo erro do Prestador, cobrança indevida ou quando a lei dispuser o contrário. Nada nestes Termos limita os direitos irrenunciáveis que a Lei nº 1.334/1998 de Defesa do Consumidor e do Usuário reconhece aos consumidores, inclusive o de reclamar perante a Secretaria de Defesa do Consumidor e do Usuário (SEDECO).`],
            ['9. Uso aceitável', `É proibido:\n- Usar o Serviço para fins ilícitos ou para registrar atividades que constituam fatos puníveis.\n- Tentar acessar contas ou dados de outros usuários, burlar os limites de cada plano ou violar a segurança do Serviço.\n- Sobrecarregar a infraestrutura, extrair dados de forma automatizada e em massa, fazer engenharia reversa ou realizar ataques.\n- Revender, sublicenciar ou compartilhar o acesso à Conta com terceiros.\n- Usar o Chat IA para fins alheios às finanças pessoais ou tentar manipulá-lo para obter informações internas do sistema.\n- Publicar na Comunidade conteúdo ilícito ou ofensivo, que infrinja direitos de terceiros ou contenha dados pessoais alheios.`],
            ['10. Inteligência artificial', `O Chat IA usa modelos de inteligência artificial de terceiros para entender mensagens de texto, fotos de comprovantes e áudios, registrar lançamentos e responder perguntas sobre os dados do Usuário.\n- As respostas e os registros podem conter erros. O Usuário deve conferir valor, data, conta e categoria de cada registro; os registros feitos pela IA podem ser revertidos por alguns segundos na própria tela e editados depois como qualquer outro.\n- As respostas da IA são informativas e não constituem consultoria financeira, contábil nem de investimentos.\n- Cada plano tem um limite mensal de mensagens e de registros por foto ou áudio; ao atingi-lo, essas funções voltam no mês seguinte ou com um plano superior.\n- O Usuário não deve enviar fotos ou áudios com dados sensíveis de terceiros nem informações que não precise registrar. Fotos e áudios são processados apenas para essa finalidade e não são guardados no Serviço (veja a Política de Privacidade).`],
            ['11. Dados do Usuário', `O Conteúdo do Usuário pertence a ele. O Usuário concede ao Prestador uma licença limitada, não exclusiva e revogável, somente para hospedar, processar e exibir esses dados a fim de prestar o Serviço. O Prestador não vende os dados nem os usa para publicidade.\nO Usuário pode corrigir seus dados, excluir sua Conta a qualquer momento em Configurações (o que apaga definitivamente suas contas, categorias e lançamentos) e, no Plano Pro, exportar e fazer backup das informações pelo sistema; nos demais planos pode pedir uma cópia pelo contato indicado.`],
            ['12. Propriedade intelectual', `O software, o design, as marcas, os textos e demais elementos do ${app} pertencem ao Prestador ou a seus licenciantes e são protegidos pela Lei nº 1.328/1998 de Direito de Autor e Conexos e demais normas aplicáveis. Estes Termos não transferem ao Usuário nenhum direito sobre eles, salvo o de usar o Serviço enquanto sua Conta estiver ativa.`],
            ['13. Disponibilidade e cópias de segurança', `O Prestador empenha esforços razoáveis para manter o Serviço disponível e os dados protegidos, mas não garante funcionamento ininterrupto nem livre de erros: pode haver manutenção, falhas de terceiros (hospedagem, e-mail, conexão) ou força maior.\nO modo sem internet guarda os registros temporariamente no aparelho até enviá-los; o Usuário deve se reconectar para concluir o envio e não apagar os dados do navegador antes. Recomenda-se exportar cópias periódicas (Plano Pro) ou solicitá-las.`],
            ['14. Limitação de responsabilidade', `Na medida permitida em lei, o Prestador não responde por danos indiretos, lucros cessantes ou perdas decorrentes de decisões tomadas com base nas informações do Serviço, de dados registrados incorretamente pelo Usuário, de erros da IA não conferidos, de falhas de terceiros ou do uso indevido da Conta. Quando a lei não permitir excluir ou limitar a responsabilidade, em especial perante consumidores, aplica-se o limite mínimo obrigatório, e a responsabilidade do Prestador, quando existir, limita-se ao valor efetivamente pago pelo Usuário nos 12 meses anteriores ao fato. Nada disso afeta os direitos irrenunciáveis do consumidor.`],
            ['15. Suspensão e encerramento', `O Prestador pode suspender ou cancelar Contas que descumpram estes Termos, que tenham uso fraudulento ou abusivo, ou por ordem de autoridade competente, avisando o Usuário sempre que possível. Se o cancelamento decorrer de descumprimento do Usuário, o período em curso não é reembolsado. O Usuário pode pedir a exportação dos seus dados (quando o plano permitir) ou a exclusão deles.`],
            ['16. Alterações nos Termos', `O Prestador pode atualizar estes Termos e a Política de Privacidade. Mudanças relevantes são informadas dentro do Serviço e será pedido novo aceite para continuar usando. A versão vigente aparece no topo de cada documento.`],
            ['17. Comunicações', `O Usuário aceita receber as comunicações eletrônicas necessárias ao Serviço (confirmação de e-mail, recuperação de senha, avisos de assinatura e de segurança, e avisos de vencimento se ativados) e ser contatado por e-mail, telefone ou WhatsApp para combinar a contratação de um plano. Os avisos de vencimento podem ser desativados em Configurações.`],
            ['18. Lei aplicável, foro e reclamações', `Estes Termos são regidos pelas leis da República do Paraguai. Diante de qualquer controvérsia, as partes tentarão resolvê-la amigavelmente, contatando primeiro o Prestador. Não havendo acordo, serão competentes os tribunais ordinários da cidade de Assunção, sem prejuízo do direito do consumidor de recorrer à SEDECO e aos foros que a Lei nº 1.334/1998 lhe reconhece.`],
            ['19. Disposições gerais', `Se alguma cláusula for declarada inválida, as demais continuam em vigor. A falta de exercício de um direito não significa renúncia. Estes Termos e a Política de Privacidade são o acordo completo entre o Usuário e o Prestador sobre o Serviço.`],
            ['20. Contato', `Dúvidas, reclamações e solicitações: ${contato}.`]
        ],
        privacidade: [
            ['1. Responsável e base legal', `O responsável pelo tratamento dos dados pessoais é o Prestador do ${app}. Contato: ${contato}.${ident}\nO tratamento respeita os direitos à intimidade e à proteção dos dados pessoais reconhecidos pela Constituição Nacional do Paraguai (arts. 33 e 36 e a garantia do habeas data do art. 135), pela Lei nº 4.868/2013 de Comércio Eletrônico, pela Lei nº 1.334/1998 de Defesa do Consumidor e do Usuário e, no que for aplicável, pela Lei nº 6.534/2020 de Proteção de Dados Pessoais Creditórios, além das demais normas vigentes na República do Paraguai.`],
            ['2. Dados que coletamos', `- Conta: nome, e-mail, senha (guardada com hash, nunca em texto), idioma, moeda, tema e data do aceite dos termos. Se você entrar com o Google: seu nome, e-mail verificado e identificador do Google.\n- Contato de contratação: telefone (somente se você solicitar um plano).\n- Dados financeiros que você registra: contas, saldos, lançamentos, categorias, orçamentos e lembretes.\n- Chat IA: suas mensagens e as respostas (para mostrar o histórico; você pode apagar as conversas) e, apenas enquanto são processados, as fotos e os áudios que enviar.\n- Uso e segurança: datas de acesso, endereço IP, tipo de navegador ou aparelho, tentativas de entrada, aparelhos conectados e contadores de uso por plano.\n- Comunidade: as publicações, comentários e imagens que você decidir publicar.`],
            ['3. Para que usamos os dados', `- Prestar o Serviço e cumprir o contrato (registro, saldos, relatórios, sincronização e modo sem internet).\n- Autenticar você, proteger a Conta e prevenir fraudes e abusos.\n- Enviar e-mails do Serviço (confirmação, recuperação de senha, avisos de assinatura) e, se você ativou, avisos de vencimento no aparelho.\n- Entrar em contato por telefone ou WhatsApp para combinar o pagamento e a ativação de um plano.\n- Gerir planos, cobranças, comprovantes e obrigações tributárias e contábeis.\n- Controlar os limites de uso de cada plano e melhorar o produto com estatísticas agregadas.\nNão vendemos seus dados nem os usamos para publicidade de terceiros.`],
            ['4. Com quem compartilhamos', `Somente com fornecedores necessários à operação do Serviço, que recebem apenas o indispensável para a sua função:\n- Hospedagem e banco de dados (Hostinger).\n- Envio de e-mails do Serviço (provedor de e-mail).\n- Login com o Google, se você escolher.\n- Fornecedores de inteligência artificial e de transcrição de áudio, somente quando você usa o Chat IA: recebem o texto, as fotos ou os áudios daquela consulta e os dados financeiros mínimos para responder.\n- Notificações push do navegador ou aparelho, se você ativar.\nTambém podemos divulgar dados quando uma autoridade competente exigir conforme a lei. Alguns fornecedores podem estar fora do Paraguai; nesse caso exigimos medidas de segurança adequadas e limitamos os dados compartilhados.`],
            ['5. Por quanto tempo guardamos', `Enquanto sua Conta estiver ativa. Ao excluí-la, apagamos seus dados pessoais e financeiros, inclusive conversas do Chat IA e aparelhos; mantemos apenas os registros de pagamento pelo prazo que as normas tributárias e contábeis exigirem, desvinculados da sua identidade na medida do possível. Fotos e áudios enviados à IA não são guardados depois de processados. Os registros técnicos de segurança são mantidos por tempo limitado.`],
            ['6. Seus direitos', `Você pode, a qualquer momento: acessar seus dados; retificá-los ou atualizá-los; pedir a exclusão; opor-se a certos tratamentos e retirar o consentimento; e exportá-los (Plano Pro em Configurações; nos demais planos, sob pedido). Esses direitos incluem a ação de habeas data prevista no art. 135 da Constituição Nacional.\nVocê pode corrigir seu perfil e excluir sua Conta diretamente em Configurações; para outras solicitações escreva para ${contato}. Responderemos em prazo razoável e, em todo caso, dentro do que a lei estabelecer. Se entender que seus direitos não foram atendidos, pode recorrer às autoridades competentes.`],
            ['7. Segurança', `Aplicamos medidas técnicas e organizacionais razoáveis: senhas com hash, conexão criptografada (HTTPS), sessões com cookies protegidos, proteção contra requisições forjadas (CSRF), limite de tentativas de entrada, isolamento dos dados por usuário e acesso restrito ao banco de dados. Nenhum sistema é infalível; se ocorrer um incidente que afete seus dados pessoais, informaremos você sem demora injustificada e tomaremos medidas para mitigá-lo.`],
            ['8. Cookies e armazenamento no seu aparelho', `Usamos um cookie técnico de sessão (necessário para manter você conectado) e o armazenamento local do navegador para preferências (por exemplo, ocultar saldos ou o tema). Para o modo sem internet e a instalação como aplicativo, o aparelho guarda uma cópia das páginas e dos seus dados e uma fila de lançamentos aguardando envio; esses dados são apagados ao sair da conta e não são compartilhados. Não usamos cookies de publicidade nem de rastreamento de terceiros.`],
            ['9. Notificações', `Os avisos de vencimento são opcionais: você os ativa e pode desativá-los em Configurações › Lembretes. Os e-mails do Serviço são apenas os necessários para operar a Conta.`],
            ['10. Menores de idade', `O Serviço não é destinado a menores de 18 anos e não coletamos seus dados intencionalmente. Se soubermos de uma conta de menor, vamos excluí-la.`],
            ['11. Alterações nesta política', `Podemos atualizar esta Política. Mudanças relevantes são informadas dentro do Serviço e será pedido novo aceite quando couber.`],
            ['12. Contato', `Dúvidas e exercício de direitos: ${contato}.`]
        ],
        aviso: 'Última atualização: outubro de 2026. Regido pela legislação da República do Paraguai.'
    };
}

module.exports = { textos, fmt };
